[package]
name = "xforge-objects"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
xforge-core.workspace = true
xforge-model.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
indexmap.workspace = true
xforge-serialization.workspace = true
