[package]
name = "xforge-model"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
xforge-core.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
indexmap.workspace = true

[dev-dependencies]
tempfile.workspace = true
