[package]
name = "xforge-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "xforge"
path = "src/main.rs"

[dependencies]
xforge-core.workspace = true
xforge-model.workspace = true
xforge-objects.workspace = true
xforge-query.workspace = true
xforge-workspace.workspace = true
xforge-scheme.workspace = true
xforge-config.workspace = true
clap = { version = "4.5", features = ["derive"] }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
